package com.openfoundry.sdk;

// This file is generated by `cargo run -p of-cli -- docs generate-sdk-java`.
// Do not edit manually.

import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.Map;

public final class OpenFoundryClient {
    private final String baseUrl;
    private final HttpClient httpClient;
    private final Map<String, String> defaultHeaders;

    public OpenFoundryClient(String baseUrl) {
        this(baseUrl, HttpClient.newHttpClient(), Map.of());
    }

    public OpenFoundryClient(String baseUrl, HttpClient httpClient, Map<String, String> headers) {
        this.baseUrl = baseUrl.endsWith("/") ? baseUrl.substring(0, baseUrl.length() - 1) : baseUrl;
        this.httpClient = httpClient;
        this.defaultHeaders = new LinkedHashMap<>(headers);
    }

    public String authRbacAssignrole(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/auth/assign-role", pathParams, queryParams, bodyJson);
    }

    public String authAuthGetme() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/auth/get-me", pathParams, queryParams, null);
    }

    public String authRbacListroles() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/auth/list-roles", pathParams, queryParams, null);
    }

    public String authAuthLogin(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/auth/login", pathParams, queryParams, bodyJson);
    }

    public String authAuthRefreshtoken(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/auth/refresh-token", pathParams, queryParams, bodyJson);
    }

    public String authAuthRegister(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/auth/register", pathParams, queryParams, bodyJson);
    }

    public String commonHealthCheck(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/common/check", pathParams, queryParams, bodyJson);
    }

    public String dataIntegrationConnectorCreateconnection(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/data-integration/create-connection", pathParams, queryParams, bodyJson);
    }

    public String dataIntegrationConnectorDeleteconnection() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("DELETE", "/api/v1/data-integration/delete-connection", pathParams, queryParams, null);
    }

    public String dataIntegrationConnectorInferschema(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/data-integration/infer-schema", pathParams, queryParams, bodyJson);
    }

    public String dataIntegrationConnectorListconnections() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/data-integration/list-connections", pathParams, queryParams, null);
    }

    public String dataIntegrationConnectorSyncconnection(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/data-integration/sync-connection", pathParams, queryParams, bodyJson);
    }

    public String dataIntegrationConnectorTestconnection(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/data-integration/test-connection", pathParams, queryParams, bodyJson);
    }

    public String datasetDatasetCreatedataset(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/datasets/create-dataset", pathParams, queryParams, bodyJson);
    }

    public String datasetDatasetDeletedataset() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("DELETE", "/api/v1/datasets/delete-dataset", pathParams, queryParams, null);
    }

    public String datasetDatasetGetdataset() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/datasets/get-dataset", pathParams, queryParams, null);
    }

    public String datasetDatasetGetversions() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/datasets/get-versions", pathParams, queryParams, null);
    }

    public String datasetDatasetListdatasets() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/datasets/list-datasets", pathParams, queryParams, null);
    }

    public String datasetDatasetPreviewdata(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/datasets/preview-data", pathParams, queryParams, bodyJson);
    }

    public String datasetDatasetUpdatedataset(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("PATCH", "/api/v1/datasets/update-dataset", pathParams, queryParams, bodyJson);
    }

    public String notebookNotebookCreatenotebook(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/notebook/create-notebook", pathParams, queryParams, bodyJson);
    }

    public String notebookKernelCreatesession(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/notebook/create-session", pathParams, queryParams, bodyJson);
    }

    public String notebookNotebookDeletenotebook() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("DELETE", "/api/v1/notebook/delete-notebook", pathParams, queryParams, null);
    }

    public String notebookNotebookGetnotebook() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/notebook/get-notebook", pathParams, queryParams, null);
    }

    public String notebookNotebookListnotebooks() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/notebook/list-notebooks", pathParams, queryParams, null);
    }

    public String notebookKernelListsessions() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/notebook/list-sessions", pathParams, queryParams, null);
    }

    public String notebookKernelStopsession(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/notebook/stop-session", pathParams, queryParams, bodyJson);
    }

    public String notebookNotebookUpdatenotebook(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("PATCH", "/api/v1/notebook/update-notebook", pathParams, queryParams, bodyJson);
    }

    public String ontologyOntologyCreatelinktype(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/ontology/create-link-type", pathParams, queryParams, bodyJson);
    }

    public String ontologyOntologyCreateobjecttype(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/ontology/create-object-type", pathParams, queryParams, bodyJson);
    }

    public String ontologyOntologyCreateproperty(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/ontology/create-property", pathParams, queryParams, bodyJson);
    }

    public String ontologyOntologyDeletelinktype() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("DELETE", "/api/v1/ontology/delete-link-type", pathParams, queryParams, null);
    }

    public String ontologyOntologyDeleteobjecttype() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("DELETE", "/api/v1/ontology/delete-object-type", pathParams, queryParams, null);
    }

    public String ontologyOntologyGetobjecttype() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/ontology/get-object-type", pathParams, queryParams, null);
    }

    public String ontologyOntologyListlinktypes() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/ontology/list-link-types", pathParams, queryParams, null);
    }

    public String ontologyOntologyListobjecttypes() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/ontology/list-object-types", pathParams, queryParams, null);
    }

    public String ontologyOntologyListproperties() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/ontology/list-properties", pathParams, queryParams, null);
    }

    public String ontologyOntologyUpdateobjecttype(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("PATCH", "/api/v1/ontology/update-object-type", pathParams, queryParams, bodyJson);
    }

    public String pipelinePipelineCreatepipeline(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/pipelines/create-pipeline", pathParams, queryParams, bodyJson);
    }

    public String pipelinePipelineDeletepipeline() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("DELETE", "/api/v1/pipelines/delete-pipeline", pathParams, queryParams, null);
    }

    public String pipelineLineageGetdatasetlineage() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/pipelines/get-dataset-lineage", pathParams, queryParams, null);
    }

    public String pipelineLineageGetfulllineage() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/pipelines/get-full-lineage", pathParams, queryParams, null);
    }

    public String pipelinePipelineGetpipeline() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/pipelines/get-pipeline", pathParams, queryParams, null);
    }

    public String pipelinePipelineGetrun() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/pipelines/get-run", pathParams, queryParams, null);
    }

    public String pipelinePipelineListpipelines() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/pipelines/list-pipelines", pathParams, queryParams, null);
    }

    public String pipelinePipelineListruns() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/pipelines/list-runs", pathParams, queryParams, null);
    }

    public String pipelineLineageRecordlineage(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/pipelines/record-lineage", pathParams, queryParams, bodyJson);
    }

    public String pipelinePipelineTriggerrun(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/pipelines/trigger-run", pathParams, queryParams, bodyJson);
    }

    public String pipelinePipelineUpdatepipeline(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("PATCH", "/api/v1/pipelines/update-pipeline", pathParams, queryParams, bodyJson);
    }

    public String queryQueryDeletesavedquery() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("DELETE", "/api/v1/queries/delete-saved-query", pathParams, queryParams, null);
    }

    public String queryQueryExecutequery(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/queries/execute-query", pathParams, queryParams, bodyJson);
    }

    public String queryQueryExplainquery(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/queries/explain-query", pathParams, queryParams, bodyJson);
    }

    public String queryQueryListsavedqueries() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/queries/list-saved-queries", pathParams, queryParams, null);
    }

    public String queryQuerySavequery(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/queries/save-query", pathParams, queryParams, bodyJson);
    }

    public String adminV2Getcontrolpanel() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v2/admin/control-panel", pathParams, queryParams, null);
    }

    public String adminV2Updatecontrolpanel(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("PUT", "/api/v2/admin/control-panel", pathParams, queryParams, bodyJson);
    }

    public String adminV2Listgroups() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v2/admin/groups", pathParams, queryParams, null);
    }

    public String adminV2Creategroup(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v2/admin/groups", pathParams, queryParams, bodyJson);
    }

    public String adminV2Updategroup(String id, String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = new LinkedHashMap<>();
        pathParams.put("id", id);
        Map<String, Object> queryParams = Map.of();
        return request("PUT", "/api/v2/admin/groups/{id}", pathParams, queryParams, bodyJson);
    }

    public String adminV2Listpermissions() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v2/admin/permissions", pathParams, queryParams, null);
    }

    public String adminV2Createpermission(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v2/admin/permissions", pathParams, queryParams, bodyJson);
    }

    public String adminV2Listpolicies() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v2/admin/policies", pathParams, queryParams, null);
    }

    public String adminV2Createpolicy(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v2/admin/policies", pathParams, queryParams, bodyJson);
    }

    public String adminV2Evaluatepolicy(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v2/admin/policies/evaluate", pathParams, queryParams, bodyJson);
    }

    public String adminV2Updatepolicy(String id, String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = new LinkedHashMap<>();
        pathParams.put("id", id);
        Map<String, Object> queryParams = Map.of();
        return request("PATCH", "/api/v2/admin/policies/{id}", pathParams, queryParams, bodyJson);
    }

    public String adminV2Listroles() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v2/admin/roles", pathParams, queryParams, null);
    }

    public String adminV2Createrole(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v2/admin/roles", pathParams, queryParams, bodyJson);
    }

    public String adminV2Updaterole(String id, String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = new LinkedHashMap<>();
        pathParams.put("id", id);
        Map<String, Object> queryParams = Map.of();
        return request("PUT", "/api/v2/admin/roles/{id}", pathParams, queryParams, bodyJson);
    }

    public String adminV2Listusers() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v2/admin/users", pathParams, queryParams, null);
    }

    public String adminV2Getcurrentuser() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v2/admin/users/me", pathParams, queryParams, null);
    }

    public String adminV2Updateuser(String id, String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = new LinkedHashMap<>();
        pathParams.put("id", id);
        Map<String, Object> queryParams = Map.of();
        return request("PATCH", "/api/v2/admin/users/{id}", pathParams, queryParams, bodyJson);
    }

    public String filesystemV2Getdatasetfilesystem(String datasetId, String path) throws IOException, InterruptedException {
        Map<String, Object> pathParams = new LinkedHashMap<>();
        pathParams.put("dataset_id", datasetId);
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (path != null) { queryParams.put("path", path); }
        return request("GET", "/api/v2/filesystem/datasets/{dataset_id}", pathParams, queryParams, null);
    }

    private String request(String method, String pathTemplate, Map<String, Object> pathParams, Map<String, Object> queryParams, String bodyJson) throws IOException, InterruptedException {
        String path = interpolatePath(pathTemplate, pathParams);
        String url = buildUrl(path, queryParams);
        HttpRequest.BodyPublisher publisher = bodyJson == null ? HttpRequest.BodyPublishers.noBody() : HttpRequest.BodyPublishers.ofString(bodyJson);
        HttpRequest.Builder builder = HttpRequest.newBuilder(URI.create(url)).method(method, publisher).header("content-type", "application/json");
        for (Map.Entry<String, String> entry : defaultHeaders.entrySet()) {
            builder.header(entry.getKey(), entry.getValue());
        }
        HttpResponse<String> response = httpClient.send(builder.build(), HttpResponse.BodyHandlers.ofString());
        if (response.statusCode() == 204) {
            return "";
        }
        if (response.statusCode() < 200 || response.statusCode() >= 300) {
            throw new IOException("OpenFoundry request failed: " + response.statusCode() + " " + response.body());
        }
        return response.body();
    }

    private String interpolatePath(String pathTemplate, Map<String, Object> pathParams) {
        String path = pathTemplate;
        for (Map.Entry<String, Object> entry : pathParams.entrySet()) {
            path = path.replace("{" + entry.getKey() + "}", urlEncode(String.valueOf(entry.getValue())));
        }
        return path;
    }

    private String buildUrl(String path, Map<String, Object> queryParams) {
        if (queryParams.isEmpty()) {
            return baseUrl + path;
        }
        StringBuilder query = new StringBuilder();
        for (Map.Entry<String, Object> entry : queryParams.entrySet()) {
            if (entry.getValue() == null) {
                continue;
            }
            if (query.length() > 0) {
                query.append('&');
            }
            query.append(urlEncode(entry.getKey())).append('=').append(urlEncode(String.valueOf(entry.getValue())));
        }
        return query.length() == 0 ? baseUrl + path : baseUrl + path + "?" + query;
    }

    private String urlEncode(String value) {
        return URLEncoder.encode(value, StandardCharsets.UTF_8);
    }
}