{{- range $serviceName, $service := .Values.services }}
{{- if $service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-foundry.fullname" (dict "root" $ "serviceName" $serviceName) }}
  namespace: {{ include "open-foundry.namespace" (dict "root" $) }}
  labels:
{{ include "open-foundry.commonLabels" (dict "root" $ "serviceName" $serviceName) | nindent 4 }}
spec:
  type: {{ default $.Values.global.service.type $service.serviceType }}
  selector:
{{ include "open-foundry.selectorLabels" (dict "root" $ "serviceName" $serviceName) | nindent 4 }}
  ports:
    - name: http
      port: {{ $service.port }}
      targetPort: http
---
{{- end }}
{{- end }}
