{{- if .Values.serviceAccount.create }}
{{- $annotations := dict -}}
{{- range $key, $value := .Values.serviceAccount.annotations }}
{{- $_ := set $annotations $key $value -}}
{{- end }}
{{- with .Values.global.deploymentFabric.multiCloud.workloadIdentity }}
{{- if .awsRoleArn }}
{{- $_ := set $annotations "eks.amazonaws.com/role-arn" .awsRoleArn -}}
{{- end }}
{{- if .gcpServiceAccount }}
{{- $_ := set $annotations "iam.gke.io/gcp-service-account" .gcpServiceAccount -}}
{{- end }}
{{- if .azureClientId }}
{{- $_ := set $annotations "azure.workload.identity/client-id" .azureClientId -}}
{{- end }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "open-foundry.serviceAccountName" (dict "root" .) }}
  namespace: {{ include "open-foundry.namespace" (dict "root" .) }}
  labels:
{{ include "open-foundry.commonLabels" (dict "root" . "serviceName" "platform") | nindent 4 }}
{{- if gt (len $annotations) 0 }}
  annotations:
{{ toYaml $annotations | indent 4 }}
{{- end }}
{{- end }}
