{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "open-foundry.serviceAccountName" (dict "root" .) }}
  namespace: {{ include "open-foundry.namespace" (dict "root" .) }}
  labels:
{{ include "open-foundry.commonLabels" (dict "root" . "serviceName" "platform") | nindent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
