// This file is generated by `cargo run -p of-cli -- docs generate-sdk-typescript`.
// Do not edit manually.

export const OPENFOUNDRY_SDK_VERSION = "0.1.0";

export interface OpenFoundryClientOptions {
  baseUrl: string;
  fetch?: typeof fetch;
  headers?: HeadersInit;
}

export type OpenFoundryRequestInit = Omit<RequestInit, 'body' | 'method'>;
export type OpenFoundryPathParams = Record<string, string | number | boolean>;
export type OpenFoundryQuery = Record<string, string | number | boolean | undefined | null>;

export interface AdminGroupsListResponse {
  count?: number;
  items?: Array<GroupResponse>;
}

export interface AdminPermissionsListResponse {
  count?: number;
  items?: Array<Permission>;
}

export interface AdminPoliciesListResponse {
  count?: number;
  items?: Array<Policy>;
}

export interface AdminRolesListResponse {
  count?: number;
  items?: Array<RoleResponse>;
}

export interface AdminUsersListResponse {
  count?: number;
  items?: Array<UserResponse>;
}

export interface AppBrandingSettings {
  accent_color?: string;
  display_name?: string;
  favicon_url?: string;
  logo_url?: string;
  primary_color?: string;
  show_powered_by?: boolean;
}

export interface AssignRoleRequest {
  role_id?: Uuid;
  user_id?: Uuid;
}

export interface AssignRoleResponse {
}

export interface Cell {
  cell_type?: string;
  created_at?: string;
  execution_count?: number;
  id?: string;
  kernel?: string;
  last_output?: Value;
  notebook_id?: string;
  position?: number;
  source?: string;
  updated_at?: string;
}

export interface CellOutput {
  content?: Value;
  execution_count?: number;
  output_type?: string;
}

export interface Column {
  data_type?: string;
  name?: string;
}

export interface ColumnMeta {
  data_type?: string;
  name?: string;
}

export interface Connection {
  config?: Record<string, string>;
  connector_type?: ConnectorType;
  created_at?: string;
  id?: Uuid;
  last_sync_at?: string;
  name?: string;
  status?: ConnectionStatus;
}

export interface ControlPanelSettings {
  allow_self_signup?: boolean;
  allowed_email_domains?: Array<string>;
  announcement_banner?: string;
  default_app_branding?: AppBrandingSettings;
  default_region?: string;
  deployment_mode?: string;
  docs_url?: string;
  maintenance_mode?: boolean;
  platform_name?: string;
  release_channel?: string;
  restricted_operations?: Array<string>;
  status_page_url?: string;
  support_email?: string;
  updated_at?: string;
  updated_by?: string;
}

export interface CreateCellRequest {
  cell_type?: string;
  kernel?: string;
  notebook_id?: string;
  position?: number;
  source?: string;
}

export interface CreateConnectionRequest {
  config?: Record<string, string>;
  connector_type?: ConnectorType;
  name?: string;
}

export interface CreateDatasetRequest {
  description?: string;
  format?: DatasetFormat;
  name?: string;
  tags?: Array<string>;
}

export interface CreateGroupRequest {
  description?: string;
  name?: string;
  role_ids?: Array<string>;
}

export interface CreateLinkTypeRequest {
  cardinality?: string;
  description?: string;
  display_name?: string;
  name?: string;
  source_type_id?: Uuid;
  target_type_id?: Uuid;
}

export interface CreateNotebookRequest {
  default_kernel?: string;
  description?: string;
  name?: string;
}

export interface CreateObjectTypeRequest {
  color?: string;
  description?: string;
  display_name?: string;
  icon?: string;
  name?: string;
  primary_key_property?: string;
}

export interface CreatePermissionRequest {
  action?: string;
  description?: string;
  resource?: string;
}

export interface CreatePipelineRequest {
  description?: string;
  name?: string;
  nodes?: Array<PipelineNode>;
}

export interface CreatePropertyRequest {
  default_value_json?: string;
  description?: string;
  display_name?: string;
  name?: string;
  object_type_id?: Uuid;
  property_type?: string;
  required?: boolean;
  unique_constraint?: boolean;
  validation_rules_json?: string;
}

export interface CreateRoleRequest {
  description?: string;
  name?: string;
  permission_ids?: Array<string>;
}

export interface CreateSessionRequest {
  kernel?: string;
  notebook_id?: string;
}

export interface Dataset {
  created_at?: string;
  current_version?: number;
  description?: string;
  format?: DatasetFormat;
  id?: Uuid;
  name?: string;
  owner_id?: Uuid;
  row_count?: number;
  schema?: Schema;
  size_bytes?: number;
  storage_path?: string;
  tags?: Array<string>;
  updated_at?: string;
}

export interface DatasetVersion {
  created_at?: string;
  message?: string;
  row_count?: number;
  size_bytes?: number;
  version?: number;
}

export interface DeleteConnectionRequest {
  id?: Uuid;
}

export interface DeleteConnectionResponse {
}

export interface DeleteDatasetRequest {
  id?: Uuid;
}

export interface DeleteDatasetResponse {
}

export interface DeleteLinkTypeRequest {
  id?: Uuid;
}

export interface DeleteLinkTypeResponse {
}

export interface DeleteNotebookRequest {
  id?: string;
}

export interface DeleteObjectTypeRequest {
  id?: Uuid;
}

export interface DeleteObjectTypeResponse {
}

export interface DeletePipelineRequest {
  id?: Uuid;
}

export interface DeletePipelineResponse {
}

export interface DeleteSavedQueryRequest {
  id?: Uuid;
}

export interface DeleteSavedQueryResponse {
}

export interface ErrorDetail {
  code?: string;
  message?: string;
  metadata?: Record<string, string>;
}

export interface EvaluatePolicyRequest {
  action?: string;
  resource?: string;
  resource_attributes?: Record<string, unknown>;
}

export interface ExecuteCellRequest {
  cell_id?: string;
}

export interface ExecuteQueryRequest {
  limit?: number;
  offset?: number;
  parameters?: Record<string, string>;
  sql?: string;
}

export interface ExplainQueryRequest {
  sql?: string;
}

export interface ExplainQueryResponse {
  logical_plan?: string;
  physical_plan?: string;
}

export interface Field {
  field_type?: FieldType;
  metadata?: Record<string, string>;
  name?: string;
  nullable?: boolean;
}

export interface FilesystemBreadcrumb {
  name?: string;
  path?: string;
}

export interface FilesystemEntry {
  content_type?: string;
  entry_type?: string;
  last_modified?: string;
  metadata?: Record<string, unknown>;
  name?: string;
  path?: string;
  size_bytes?: number;
  storage_path?: string;
}

export interface FilesystemListResponse {
  active_branch?: string;
  breadcrumbs?: Array<FilesystemBreadcrumb>;
  current_version?: number;
  dataset_id?: string;
  entries?: Array<FilesystemEntry>;
  items?: Array<FilesystemEntry>;
  requested_path?: string;
  root?: string;
  sections?: FilesystemSections;
}

export interface FilesystemSections {
  branches?: number;
  versions?: number;
  views?: number;
}

export interface GetDatasetLineageRequest {
  dataset_id?: Uuid;
}

export interface GetDatasetRequest {
  id?: Uuid;
}

export interface GetFullLineageRequest {
}

export interface GetMeRequest {
}

export interface GetNotebookRequest {
  id?: string;
}

export interface GetObjectTypeRequest {
  id?: Uuid;
}

export interface GetPipelineRequest {
  id?: Uuid;
}

export interface GetRunRequest {
  id?: Uuid;
}

export interface GetVersionsRequest {
  dataset_id?: Uuid;
}

export interface GetVersionsResponse {
  versions?: Array<DatasetVersion>;
}

export interface GroupResponse {
  created_at?: string;
  description?: string;
  id?: string;
  member_count?: number;
  name?: string;
  role_ids?: Array<string>;
  roles?: Array<string>;
}

export interface HealthCheckRequest {
  service?: string;
}

export interface HealthCheckResponse {
}

export interface InferSchemaRequest {
  connection_id?: Uuid;
  table_name?: string;
}

export interface InferSchemaResponse {
  columns?: Array<InferredColumn>;
}

export interface InferredColumn {
  inferred_type?: string;
  name?: string;
  nullable?: boolean;
  source_type?: string;
}

export interface LineageEdge {
  node_id?: string;
  pipeline_id?: Uuid;
  source_dataset_id?: Uuid;
  target_dataset_id?: Uuid;
}

export interface LineageGraph {
  edges?: Array<LineageEdge>;
  nodes?: Array<LineageNode>;
}

export interface LineageNode {
  dataset_id?: Uuid;
}

export interface LinkType {
  cardinality?: string;
  created_at?: string;
  description?: string;
  display_name?: string;
  id?: Uuid;
  name?: string;
  owner_id?: Uuid;
  source_type_id?: Uuid;
  target_type_id?: Uuid;
  updated_at?: string;
}

export interface ListConnectionsRequest {
  pagination?: PageRequest;
}

export interface ListConnectionsResponse {
  connections?: Array<Connection>;
  pagination?: PageResponse;
}

export interface ListDatasetsRequest {
  pagination?: PageRequest;
  search?: string;
  tags?: Array<string>;
}

export interface ListDatasetsResponse {
  datasets?: Array<Dataset>;
  pagination?: PageResponse;
}

export interface ListLinkTypesRequest {
  object_type_id?: Uuid;
  pagination?: PageRequest;
}

export interface ListLinkTypesResponse {
  link_types?: Array<LinkType>;
  pagination?: PageResponse;
}

export interface ListNotebooksRequest {
  page?: number;
  per_page?: number;
  search?: string;
}

export interface ListNotebooksResponse {
  data?: Array<Notebook>;
  page?: number;
  per_page?: number;
  total?: number;
}

export interface ListObjectTypesRequest {
  pagination?: PageRequest;
  search?: string;
}

export interface ListObjectTypesResponse {
  object_types?: Array<ObjectType>;
  pagination?: PageResponse;
}

export interface ListPipelinesRequest {
  pagination?: PageRequest;
  search?: string;
}

export interface ListPipelinesResponse {
  pagination?: PageResponse;
  pipelines?: Array<Pipeline>;
}

export interface ListPropertiesRequest {
  object_type_id?: Uuid;
}

export interface ListPropertiesResponse {
  properties?: Array<Property>;
}

export interface ListRolesRequest {
}

export interface ListRolesResponse {
  roles?: Array<Role>;
}

export interface ListRunsRequest {
  pagination?: PageRequest;
  pipeline_id?: Uuid;
}

export interface ListRunsResponse {
  pagination?: PageResponse;
  runs?: Array<PipelineRun>;
}

export interface ListSavedQueriesRequest {
  pagination?: PageRequest;
  search?: string;
}

export interface ListSavedQueriesResponse {
  pagination?: PageResponse;
  queries?: Array<SavedQuery>;
}

export interface ListSessionsRequest {
  notebook_id?: string;
}

export interface ListSessionsResponse {
  data?: Array<Session>;
}

export interface LoginRequest {
  email?: string;
  password?: string;
}

export interface Notebook {
  created_at?: string;
  default_kernel?: string;
  description?: string;
  id?: string;
  name?: string;
  owner_id?: string;
  updated_at?: string;
}

export interface ObjectType {
  color?: string;
  created_at?: string;
  description?: string;
  display_name?: string;
  icon?: string;
  id?: Uuid;
  name?: string;
  owner_id?: Uuid;
  primary_key_property?: string;
  updated_at?: string;
}

export interface PageRequest {
  page?: number;
  per_page?: number;
}

export interface PageResponse {
  page?: number;
  per_page?: number;
  total?: number;
  total_pages?: number;
}

export interface Permission {
  action?: string;
  created_at?: string;
  description?: string;
  id?: string;
  resource?: string;
}

export interface Pipeline {
  created_at?: string;
  description?: string;
  id?: Uuid;
  name?: string;
  nodes?: Array<PipelineNode>;
  owner_id?: Uuid;
  status?: string;
  updated_at?: string;
}

export interface PipelineNode {
  config_json?: string;
  depends_on?: Array<string>;
  id?: string;
  input_dataset_ids?: Array<Uuid>;
  label?: string;
  output_dataset_id?: Uuid;
  transform_type?: string;
}

export interface PipelineRun {
  error_message?: string;
  finished_at?: string;
  id?: Uuid;
  node_results_json?: string;
  pipeline_id?: Uuid;
  started_at?: string;
  started_by?: Uuid;
  status?: string;
}

export interface Policy {
  action?: string;
  conditions?: Record<string, unknown>;
  created_at?: string;
  created_by?: string;
  description?: string;
  effect?: string;
  enabled?: boolean;
  id?: string;
  name?: string;
  resource?: string;
  row_filter?: string;
  updated_at?: string;
}

export interface PolicyEvaluationResult {
  allowed?: boolean;
  deny_policy_ids?: Array<string>;
  matched_policy_ids?: Array<string>;
  row_filter?: string;
}

export interface PreviewDataRequest {
  dataset_id?: Uuid;
  limit?: number;
  offset?: number;
}

export interface PreviewDataResponse {
  columns?: Array<Column>;
  rows?: Array<Row>;
  total_rows?: number;
}

export interface Property {
  created_at?: string;
  default_value_json?: string;
  description?: string;
  display_name?: string;
  id?: Uuid;
  name?: string;
  object_type_id?: Uuid;
  property_type?: string;
  required?: boolean;
  unique_constraint?: boolean;
  updated_at?: string;
  validation_rules_json?: string;
}

export interface QueryResult {
  columns?: Array<ColumnMeta>;
  execution_time_ms?: number;
  rows?: Array<RowData>;
  rows_scanned?: number;
  total_rows?: number;
}

export interface RecordLineageRequest {
  node_id?: string;
  pipeline_id?: Uuid;
  source_dataset_id?: Uuid;
  target_dataset_id?: Uuid;
}

export interface RecordLineageResponse {
}

export interface RefreshRequest {
  refresh_token?: string;
}

export interface RegisterRequest {
  email?: string;
  name?: string;
  password?: string;
}

export interface RegisterResponse {
  user_id?: Uuid;
}

export interface Role {
  description?: string;
  id?: Uuid;
  name?: string;
}

export interface RoleResponse {
  created_at?: string;
  description?: string;
  id?: string;
  name?: string;
  permission_ids?: Array<string>;
  permissions?: Array<string>;
}

export interface Row {
  values?: Record<string, string>;
}

export interface RowData {
  values?: Array<string>;
}

export interface SaveQueryRequest {
  description?: string;
  name?: string;
  sql?: string;
}

export interface SavedQuery {
  created_at?: string;
  description?: string;
  id?: Uuid;
  name?: string;
  owner_id?: Uuid;
  sql?: string;
  updated_at?: string;
}

export interface Schema {
  fields?: Array<Field>;
}

export interface Session {
  created_at?: string;
  id?: string;
  kernel?: string;
  last_activity?: string;
  notebook_id?: string;
  started_by?: string;
  status?: string;
}

export interface StopSessionRequest {
  session_id?: string;
}

export interface SyncConnectionRequest {
  connection_id?: Uuid;
  table_name?: string;
  target_dataset_id?: Uuid;
}

export interface SyncStatus {
  error?: string;
  rows_synced?: number;
  status?: string;
}

export interface TestConnectionRequest {
  id?: Uuid;
}

export interface TestConnectionResponse {
  message?: string;
  success?: boolean;
}

export interface Timestamps {
  created_at?: string;
  updated_at?: string;
}

export interface TokenPair {
  access_token?: string;
  expires_in?: number;
  refresh_token?: string;
}

export interface TriggerRunRequest {
  pipeline_id?: Uuid;
}

export interface UpdateCellRequest {
  cell_id?: string;
  cell_type?: string;
  kernel?: string;
  position?: number;
  source?: string;
}

export interface UpdateControlPanelRequest {
  allow_self_signup?: boolean;
  allowed_email_domains?: Array<string>;
  announcement_banner?: string;
  default_app_branding?: AppBrandingSettings;
  default_region?: string;
  deployment_mode?: string;
  docs_url?: string;
  maintenance_mode?: boolean;
  platform_name?: string;
  release_channel?: string;
  restricted_operations?: Array<string>;
  status_page_url?: string;
  support_email?: string;
}

export interface UpdateDatasetRequest {
  description?: string;
  id?: Uuid;
  name?: string;
  tags?: Array<string>;
}

export interface UpdateGroupRequest {
  description?: string;
  role_ids?: Array<string>;
}

export interface UpdateNotebookRequest {
  default_kernel?: string;
  description?: string;
  id?: string;
  name?: string;
}

export interface UpdateObjectTypeRequest {
  color?: string;
  description?: string;
  display_name?: string;
  icon?: string;
  id?: Uuid;
  primary_key_property?: string;
}

export interface UpdatePipelineRequest {
  description?: string;
  id?: Uuid;
  name?: string;
  nodes?: Array<PipelineNode>;
}

export interface UpdateRoleRequest {
  description?: string;
  permission_ids?: Array<string>;
}

export interface UpdateUserRequest {
  attributes?: Record<string, unknown>;
  is_active?: boolean;
  mfa_enforced?: boolean;
  name?: string;
  organization_id?: string;
}

export interface UpsertPolicyRequest {
  action?: string;
  conditions?: Record<string, unknown>;
  description?: string;
  effect?: string;
  enabled?: boolean;
  name?: string;
  resource?: string;
  row_filter?: string;
}

export interface UserInfo {
  email?: string;
  id?: Uuid;
  name?: string;
  roles?: Array<string>;
}

export interface UserResponse {
  attributes?: Record<string, unknown>;
  auth_source?: string;
  created_at?: string;
  email?: string;
  groups?: Array<string>;
  id?: string;
  is_active?: boolean;
  mfa_enabled?: boolean;
  mfa_enforced?: boolean;
  name?: string;
  organization_id?: string;
  permissions?: Array<string>;
  roles?: Array<string>;
}

export interface Uuid {
  value?: string;
}

export type ConnectionStatus = string;

export type ConnectorType = string;

export type DatasetFormat = string;

export type FieldType = string;

export type Value = unknown;

export class OpenFoundryClient {
  private readonly baseUrl: string;
  private readonly fetchImpl: typeof fetch;
  private readonly defaultHeaders: HeadersInit;

  constructor(options: OpenFoundryClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/$/, '');
    this.fetchImpl = options.fetch ?? fetch;
    this.defaultHeaders = options.headers ?? {};
  }

  async authRbacAssignrole(body: AssignRoleRequest, init: OpenFoundryRequestInit = {}): Promise<AssignRoleResponse> {
    return this.request<AssignRoleResponse>("POST", "/api/v1/auth/assign-role", undefined, undefined, body, init);
  }

  async authAuthGetme(init: OpenFoundryRequestInit = {}): Promise<UserInfo> {
    return this.request<UserInfo>("GET", "/api/v1/auth/get-me", undefined, undefined, undefined, init);
  }

  async authRbacListroles(init: OpenFoundryRequestInit = {}): Promise<ListRolesResponse> {
    return this.request<ListRolesResponse>("GET", "/api/v1/auth/list-roles", undefined, undefined, undefined, init);
  }

  async authAuthLogin(body: LoginRequest, init: OpenFoundryRequestInit = {}): Promise<TokenPair> {
    return this.request<TokenPair>("POST", "/api/v1/auth/login", undefined, undefined, body, init);
  }

  async authAuthRefreshtoken(body: RefreshRequest, init: OpenFoundryRequestInit = {}): Promise<TokenPair> {
    return this.request<TokenPair>("POST", "/api/v1/auth/refresh-token", undefined, undefined, body, init);
  }

  async authAuthRegister(body: RegisterRequest, init: OpenFoundryRequestInit = {}): Promise<RegisterResponse> {
    return this.request<RegisterResponse>("POST", "/api/v1/auth/register", undefined, undefined, body, init);
  }

  async commonHealthCheck(body: HealthCheckRequest, init: OpenFoundryRequestInit = {}): Promise<HealthCheckResponse> {
    return this.request<HealthCheckResponse>("POST", "/api/v1/common/check", undefined, undefined, body, init);
  }

  async dataIntegrationConnectorCreateconnection(body: CreateConnectionRequest, init: OpenFoundryRequestInit = {}): Promise<Connection> {
    return this.request<Connection>("POST", "/api/v1/data-integration/create-connection", undefined, undefined, body, init);
  }

  async dataIntegrationConnectorDeleteconnection(init: OpenFoundryRequestInit = {}): Promise<DeleteConnectionResponse> {
    return this.request<DeleteConnectionResponse>("DELETE", "/api/v1/data-integration/delete-connection", undefined, undefined, undefined, init);
  }

  async dataIntegrationConnectorInferschema(body: InferSchemaRequest, init: OpenFoundryRequestInit = {}): Promise<InferSchemaResponse> {
    return this.request<InferSchemaResponse>("POST", "/api/v1/data-integration/infer-schema", undefined, undefined, body, init);
  }

  async dataIntegrationConnectorListconnections(init: OpenFoundryRequestInit = {}): Promise<ListConnectionsResponse> {
    return this.request<ListConnectionsResponse>("GET", "/api/v1/data-integration/list-connections", undefined, undefined, undefined, init);
  }

  async dataIntegrationConnectorSyncconnection(body: SyncConnectionRequest, init: OpenFoundryRequestInit = {}): Promise<SyncStatus> {
    return this.request<SyncStatus>("POST", "/api/v1/data-integration/sync-connection", undefined, undefined, body, init);
  }

  async dataIntegrationConnectorTestconnection(body: TestConnectionRequest, init: OpenFoundryRequestInit = {}): Promise<TestConnectionResponse> {
    return this.request<TestConnectionResponse>("POST", "/api/v1/data-integration/test-connection", undefined, undefined, body, init);
  }

  async datasetDatasetCreatedataset(body: CreateDatasetRequest, init: OpenFoundryRequestInit = {}): Promise<Dataset> {
    return this.request<Dataset>("POST", "/api/v1/datasets/create-dataset", undefined, undefined, body, init);
  }

  async datasetDatasetDeletedataset(init: OpenFoundryRequestInit = {}): Promise<DeleteDatasetResponse> {
    return this.request<DeleteDatasetResponse>("DELETE", "/api/v1/datasets/delete-dataset", undefined, undefined, undefined, init);
  }

  async datasetDatasetGetdataset(init: OpenFoundryRequestInit = {}): Promise<Dataset> {
    return this.request<Dataset>("GET", "/api/v1/datasets/get-dataset", undefined, undefined, undefined, init);
  }

  async datasetDatasetGetversions(init: OpenFoundryRequestInit = {}): Promise<GetVersionsResponse> {
    return this.request<GetVersionsResponse>("GET", "/api/v1/datasets/get-versions", undefined, undefined, undefined, init);
  }

  async datasetDatasetListdatasets(init: OpenFoundryRequestInit = {}): Promise<ListDatasetsResponse> {
    return this.request<ListDatasetsResponse>("GET", "/api/v1/datasets/list-datasets", undefined, undefined, undefined, init);
  }

  async datasetDatasetPreviewdata(body: PreviewDataRequest, init: OpenFoundryRequestInit = {}): Promise<PreviewDataResponse> {
    return this.request<PreviewDataResponse>("POST", "/api/v1/datasets/preview-data", undefined, undefined, body, init);
  }

  async datasetDatasetUpdatedataset(body: UpdateDatasetRequest, init: OpenFoundryRequestInit = {}): Promise<Dataset> {
    return this.request<Dataset>("PATCH", "/api/v1/datasets/update-dataset", undefined, undefined, body, init);
  }

  async notebookNotebookCreatenotebook(body: CreateNotebookRequest, init: OpenFoundryRequestInit = {}): Promise<Notebook> {
    return this.request<Notebook>("POST", "/api/v1/notebook/create-notebook", undefined, undefined, body, init);
  }

  async notebookKernelCreatesession(body: CreateSessionRequest, init: OpenFoundryRequestInit = {}): Promise<Session> {
    return this.request<Session>("POST", "/api/v1/notebook/create-session", undefined, undefined, body, init);
  }

  async notebookNotebookDeletenotebook(init: OpenFoundryRequestInit = {}): Promise<Notebook> {
    return this.request<Notebook>("DELETE", "/api/v1/notebook/delete-notebook", undefined, undefined, undefined, init);
  }

  async notebookNotebookGetnotebook(init: OpenFoundryRequestInit = {}): Promise<Notebook> {
    return this.request<Notebook>("GET", "/api/v1/notebook/get-notebook", undefined, undefined, undefined, init);
  }

  async notebookNotebookListnotebooks(init: OpenFoundryRequestInit = {}): Promise<ListNotebooksResponse> {
    return this.request<ListNotebooksResponse>("GET", "/api/v1/notebook/list-notebooks", undefined, undefined, undefined, init);
  }

  async notebookKernelListsessions(init: OpenFoundryRequestInit = {}): Promise<ListSessionsResponse> {
    return this.request<ListSessionsResponse>("GET", "/api/v1/notebook/list-sessions", undefined, undefined, undefined, init);
  }

  async notebookKernelStopsession(body: StopSessionRequest, init: OpenFoundryRequestInit = {}): Promise<Session> {
    return this.request<Session>("POST", "/api/v1/notebook/stop-session", undefined, undefined, body, init);
  }

  async notebookNotebookUpdatenotebook(body: UpdateNotebookRequest, init: OpenFoundryRequestInit = {}): Promise<Notebook> {
    return this.request<Notebook>("PATCH", "/api/v1/notebook/update-notebook", undefined, undefined, body, init);
  }

  async ontologyOntologyCreatelinktype(body: CreateLinkTypeRequest, init: OpenFoundryRequestInit = {}): Promise<LinkType> {
    return this.request<LinkType>("POST", "/api/v1/ontology/create-link-type", undefined, undefined, body, init);
  }

  async ontologyOntologyCreateobjecttype(body: CreateObjectTypeRequest, init: OpenFoundryRequestInit = {}): Promise<ObjectType> {
    return this.request<ObjectType>("POST", "/api/v1/ontology/create-object-type", undefined, undefined, body, init);
  }

  async ontologyOntologyCreateproperty(body: CreatePropertyRequest, init: OpenFoundryRequestInit = {}): Promise<Property> {
    return this.request<Property>("POST", "/api/v1/ontology/create-property", undefined, undefined, body, init);
  }

  async ontologyOntologyDeletelinktype(init: OpenFoundryRequestInit = {}): Promise<DeleteLinkTypeResponse> {
    return this.request<DeleteLinkTypeResponse>("DELETE", "/api/v1/ontology/delete-link-type", undefined, undefined, undefined, init);
  }

  async ontologyOntologyDeleteobjecttype(init: OpenFoundryRequestInit = {}): Promise<DeleteObjectTypeResponse> {
    return this.request<DeleteObjectTypeResponse>("DELETE", "/api/v1/ontology/delete-object-type", undefined, undefined, undefined, init);
  }

  async ontologyOntologyGetobjecttype(init: OpenFoundryRequestInit = {}): Promise<ObjectType> {
    return this.request<ObjectType>("GET", "/api/v1/ontology/get-object-type", undefined, undefined, undefined, init);
  }

  async ontologyOntologyListlinktypes(init: OpenFoundryRequestInit = {}): Promise<ListLinkTypesResponse> {
    return this.request<ListLinkTypesResponse>("GET", "/api/v1/ontology/list-link-types", undefined, undefined, undefined, init);
  }

  async ontologyOntologyListobjecttypes(init: OpenFoundryRequestInit = {}): Promise<ListObjectTypesResponse> {
    return this.request<ListObjectTypesResponse>("GET", "/api/v1/ontology/list-object-types", undefined, undefined, undefined, init);
  }

  async ontologyOntologyListproperties(init: OpenFoundryRequestInit = {}): Promise<ListPropertiesResponse> {
    return this.request<ListPropertiesResponse>("GET", "/api/v1/ontology/list-properties", undefined, undefined, undefined, init);
  }

  async ontologyOntologyUpdateobjecttype(body: UpdateObjectTypeRequest, init: OpenFoundryRequestInit = {}): Promise<ObjectType> {
    return this.request<ObjectType>("PATCH", "/api/v1/ontology/update-object-type", undefined, undefined, body, init);
  }

  async pipelinePipelineCreatepipeline(body: CreatePipelineRequest, init: OpenFoundryRequestInit = {}): Promise<Pipeline> {
    return this.request<Pipeline>("POST", "/api/v1/pipelines/create-pipeline", undefined, undefined, body, init);
  }

  async pipelinePipelineDeletepipeline(init: OpenFoundryRequestInit = {}): Promise<DeletePipelineResponse> {
    return this.request<DeletePipelineResponse>("DELETE", "/api/v1/pipelines/delete-pipeline", undefined, undefined, undefined, init);
  }

  async pipelineLineageGetdatasetlineage(init: OpenFoundryRequestInit = {}): Promise<LineageGraph> {
    return this.request<LineageGraph>("GET", "/api/v1/pipelines/get-dataset-lineage", undefined, undefined, undefined, init);
  }

  async pipelineLineageGetfulllineage(init: OpenFoundryRequestInit = {}): Promise<LineageGraph> {
    return this.request<LineageGraph>("GET", "/api/v1/pipelines/get-full-lineage", undefined, undefined, undefined, init);
  }

  async pipelinePipelineGetpipeline(init: OpenFoundryRequestInit = {}): Promise<Pipeline> {
    return this.request<Pipeline>("GET", "/api/v1/pipelines/get-pipeline", undefined, undefined, undefined, init);
  }

  async pipelinePipelineGetrun(init: OpenFoundryRequestInit = {}): Promise<PipelineRun> {
    return this.request<PipelineRun>("GET", "/api/v1/pipelines/get-run", undefined, undefined, undefined, init);
  }

  async pipelinePipelineListpipelines(init: OpenFoundryRequestInit = {}): Promise<ListPipelinesResponse> {
    return this.request<ListPipelinesResponse>("GET", "/api/v1/pipelines/list-pipelines", undefined, undefined, undefined, init);
  }

  async pipelinePipelineListruns(init: OpenFoundryRequestInit = {}): Promise<ListRunsResponse> {
    return this.request<ListRunsResponse>("GET", "/api/v1/pipelines/list-runs", undefined, undefined, undefined, init);
  }

  async pipelineLineageRecordlineage(body: RecordLineageRequest, init: OpenFoundryRequestInit = {}): Promise<RecordLineageResponse> {
    return this.request<RecordLineageResponse>("POST", "/api/v1/pipelines/record-lineage", undefined, undefined, body, init);
  }

  async pipelinePipelineTriggerrun(body: TriggerRunRequest, init: OpenFoundryRequestInit = {}): Promise<PipelineRun> {
    return this.request<PipelineRun>("POST", "/api/v1/pipelines/trigger-run", undefined, undefined, body, init);
  }

  async pipelinePipelineUpdatepipeline(body: UpdatePipelineRequest, init: OpenFoundryRequestInit = {}): Promise<Pipeline> {
    return this.request<Pipeline>("PATCH", "/api/v1/pipelines/update-pipeline", undefined, undefined, body, init);
  }

  async queryQueryDeletesavedquery(init: OpenFoundryRequestInit = {}): Promise<DeleteSavedQueryResponse> {
    return this.request<DeleteSavedQueryResponse>("DELETE", "/api/v1/queries/delete-saved-query", undefined, undefined, undefined, init);
  }

  async queryQueryExecutequery(body: ExecuteQueryRequest, init: OpenFoundryRequestInit = {}): Promise<QueryResult> {
    return this.request<QueryResult>("POST", "/api/v1/queries/execute-query", undefined, undefined, body, init);
  }

  async queryQueryExplainquery(body: ExplainQueryRequest, init: OpenFoundryRequestInit = {}): Promise<ExplainQueryResponse> {
    return this.request<ExplainQueryResponse>("POST", "/api/v1/queries/explain-query", undefined, undefined, body, init);
  }

  async queryQueryListsavedqueries(init: OpenFoundryRequestInit = {}): Promise<ListSavedQueriesResponse> {
    return this.request<ListSavedQueriesResponse>("GET", "/api/v1/queries/list-saved-queries", undefined, undefined, undefined, init);
  }

  async queryQuerySavequery(body: SaveQueryRequest, init: OpenFoundryRequestInit = {}): Promise<SavedQuery> {
    return this.request<SavedQuery>("POST", "/api/v1/queries/save-query", undefined, undefined, body, init);
  }

  async adminV2Getcontrolpanel(init: OpenFoundryRequestInit = {}): Promise<ControlPanelSettings> {
    return this.request<ControlPanelSettings>("GET", "/api/v2/admin/control-panel", undefined, undefined, undefined, init);
  }

  async adminV2Updatecontrolpanel(body: UpdateControlPanelRequest, init: OpenFoundryRequestInit = {}): Promise<ControlPanelSettings> {
    return this.request<ControlPanelSettings>("PUT", "/api/v2/admin/control-panel", undefined, undefined, body, init);
  }

  async adminV2Listgroups(init: OpenFoundryRequestInit = {}): Promise<AdminGroupsListResponse> {
    return this.request<AdminGroupsListResponse>("GET", "/api/v2/admin/groups", undefined, undefined, undefined, init);
  }

  async adminV2Creategroup(body: CreateGroupRequest, init: OpenFoundryRequestInit = {}): Promise<GroupResponse> {
    return this.request<GroupResponse>("POST", "/api/v2/admin/groups", undefined, undefined, body, init);
  }

  async adminV2Updategroup(id: string, body: UpdateGroupRequest, init: OpenFoundryRequestInit = {}): Promise<GroupResponse> {
    return this.request<GroupResponse>("PUT", "/api/v2/admin/groups/{id}", { "id": id }, undefined, body, init);
  }

  async adminV2Listpermissions(init: OpenFoundryRequestInit = {}): Promise<AdminPermissionsListResponse> {
    return this.request<AdminPermissionsListResponse>("GET", "/api/v2/admin/permissions", undefined, undefined, undefined, init);
  }

  async adminV2Createpermission(body: CreatePermissionRequest, init: OpenFoundryRequestInit = {}): Promise<Permission> {
    return this.request<Permission>("POST", "/api/v2/admin/permissions", undefined, undefined, body, init);
  }

  async adminV2Listpolicies(init: OpenFoundryRequestInit = {}): Promise<AdminPoliciesListResponse> {
    return this.request<AdminPoliciesListResponse>("GET", "/api/v2/admin/policies", undefined, undefined, undefined, init);
  }

  async adminV2Createpolicy(body: UpsertPolicyRequest, init: OpenFoundryRequestInit = {}): Promise<Policy> {
    return this.request<Policy>("POST", "/api/v2/admin/policies", undefined, undefined, body, init);
  }

  async adminV2Evaluatepolicy(body: EvaluatePolicyRequest, init: OpenFoundryRequestInit = {}): Promise<PolicyEvaluationResult> {
    return this.request<PolicyEvaluationResult>("POST", "/api/v2/admin/policies/evaluate", undefined, undefined, body, init);
  }

  async adminV2Updatepolicy(id: string, body: UpsertPolicyRequest, init: OpenFoundryRequestInit = {}): Promise<Policy> {
    return this.request<Policy>("PATCH", "/api/v2/admin/policies/{id}", { "id": id }, undefined, body, init);
  }

  async adminV2Listroles(init: OpenFoundryRequestInit = {}): Promise<AdminRolesListResponse> {
    return this.request<AdminRolesListResponse>("GET", "/api/v2/admin/roles", undefined, undefined, undefined, init);
  }

  async adminV2Createrole(body: CreateRoleRequest, init: OpenFoundryRequestInit = {}): Promise<RoleResponse> {
    return this.request<RoleResponse>("POST", "/api/v2/admin/roles", undefined, undefined, body, init);
  }

  async adminV2Updaterole(id: string, body: UpdateRoleRequest, init: OpenFoundryRequestInit = {}): Promise<RoleResponse> {
    return this.request<RoleResponse>("PUT", "/api/v2/admin/roles/{id}", { "id": id }, undefined, body, init);
  }

  async adminV2Listusers(init: OpenFoundryRequestInit = {}): Promise<AdminUsersListResponse> {
    return this.request<AdminUsersListResponse>("GET", "/api/v2/admin/users", undefined, undefined, undefined, init);
  }

  async adminV2Getcurrentuser(init: OpenFoundryRequestInit = {}): Promise<UserResponse> {
    return this.request<UserResponse>("GET", "/api/v2/admin/users/me", undefined, undefined, undefined, init);
  }

  async adminV2Updateuser(id: string, body: UpdateUserRequest, init: OpenFoundryRequestInit = {}): Promise<UserResponse> {
    return this.request<UserResponse>("PATCH", "/api/v2/admin/users/{id}", { "id": id }, undefined, body, init);
  }

  async filesystemV2Getdatasetfilesystem(dataset_id: string, query: { path?: string } = {}, init: OpenFoundryRequestInit = {}): Promise<FilesystemListResponse> {
    return this.request<FilesystemListResponse>("GET", "/api/v2/filesystem/datasets/{dataset_id}", { "dataset_id": dataset_id }, query, undefined, init);
  }

  private async request<TResponse>(
    method: string,
    pathTemplate: string,
    pathParams: OpenFoundryPathParams | undefined,
    query: OpenFoundryQuery | undefined,
    body: unknown,
    init: OpenFoundryRequestInit,
  ): Promise<TResponse> {
    const path = this.interpolatePath(pathTemplate, pathParams);
    const url = new URL(`${this.baseUrl}${path}`);
    if (query) {
      for (const [key, value] of Object.entries(query)) {
        if (value !== undefined && value !== null) {
          url.searchParams.set(key, String(value));
        }
      }
    }
    const response = await this.fetchImpl(url.toString(), {
      ...init,
      method,
      headers: {
        'content-type': 'application/json',
        ...this.defaultHeaders,
        ...(init.headers ?? {}),
      },
      body: body === undefined ? undefined : JSON.stringify(body),
    });

    if (!response.ok) {
      const message = await response.text();
      throw new Error(`OpenFoundry request failed: ${response.status} ${message}`.trim());
    }

    if (response.status === 204) {
      return undefined as TResponse;
    }

    return (await response.json()) as TResponse;
  }

  private interpolatePath(pathTemplate: string, pathParams: OpenFoundryPathParams | undefined): string {
    if (!pathParams) {
      return pathTemplate;
    }
    return Object.entries(pathParams).reduce(
      (path, [key, value]) => path.replace(`{${key}}`, encodeURIComponent(String(value))),
      pathTemplate,
    );
  }
}