# This file is generated by `cargo run -p of-cli -- docs generate-sdk-python`.
# Do not edit manually.
from __future__ import annotations

import json
import urllib.error
import urllib.parse
import urllib.request
from typing import Any, Mapping

from . import models

class OpenFoundryClient:
    def __init__(self, base_url: str, headers: Mapping[str, str] | None = None) -> None:
        self.base_url = base_url.rstrip('/')
        self.default_headers = dict(headers or {})

    def _request(
        self,
        method: str,
        path_template: str,
        path_params: Mapping[str, Any] | None = None,
        query: Mapping[str, Any] | None = None,
        body: Any = None,
        headers: Mapping[str, str] | None = None,
    ) -> Any:
        path = path_template
        for key, value in (path_params or {}).items():
            path = path.replace('{' + key + '}', urllib.parse.quote(str(value), safe=''))
        url = f"{self.base_url}{path}"
        if query:
            filtered = {key: value for key, value in query.items() if value is not None}
            if filtered:
                url = f"{url}?{urllib.parse.urlencode(filtered)}"
        payload = None
        request_headers = {'content-type': 'application/json', **self.default_headers, **dict(headers or {})}
        if body is not None:
            payload = json.dumps(models.serialize_model(body)).encode('utf-8')
        request = urllib.request.Request(url=url, data=payload, method=method, headers=request_headers)
        try:
            with urllib.request.urlopen(request) as response:
                raw = response.read()
                if response.status == 204 or not raw:
                    return None
                return json.loads(raw.decode('utf-8'))
        except urllib.error.HTTPError as error:
            message = error.read().decode('utf-8', errors='replace')
            raise RuntimeError(f'OpenFoundry request failed: {error.code} {message}'.strip()) from error

    def auth_rbac_assignrole(self, body: models.AssignRoleRequest, headers: Mapping[str, str] | None = None) -> models.AssignRoleResponse:
        payload = self._request("POST", "/api/v1/auth/assign-role", None, None, body, headers=headers)
        return models.deserialize_model(models.AssignRoleResponse, payload)

    def auth_auth_getme(self, headers: Mapping[str, str] | None = None) -> models.UserInfo:
        payload = self._request("GET", "/api/v1/auth/get-me", None, None, None, headers=headers)
        return models.deserialize_model(models.UserInfo, payload)

    def auth_rbac_listroles(self, headers: Mapping[str, str] | None = None) -> models.ListRolesResponse:
        payload = self._request("GET", "/api/v1/auth/list-roles", None, None, None, headers=headers)
        return models.deserialize_model(models.ListRolesResponse, payload)

    def auth_auth_login(self, body: models.LoginRequest, headers: Mapping[str, str] | None = None) -> models.TokenPair:
        payload = self._request("POST", "/api/v1/auth/login", None, None, body, headers=headers)
        return models.deserialize_model(models.TokenPair, payload)

    def auth_auth_refreshtoken(self, body: models.RefreshRequest, headers: Mapping[str, str] | None = None) -> models.TokenPair:
        payload = self._request("POST", "/api/v1/auth/refresh-token", None, None, body, headers=headers)
        return models.deserialize_model(models.TokenPair, payload)

    def auth_auth_register(self, body: models.RegisterRequest, headers: Mapping[str, str] | None = None) -> models.RegisterResponse:
        payload = self._request("POST", "/api/v1/auth/register", None, None, body, headers=headers)
        return models.deserialize_model(models.RegisterResponse, payload)

    def common_health_check(self, body: models.HealthCheckRequest, headers: Mapping[str, str] | None = None) -> models.HealthCheckResponse:
        payload = self._request("POST", "/api/v1/common/check", None, None, body, headers=headers)
        return models.deserialize_model(models.HealthCheckResponse, payload)

    def data_integration_connector_createconnection(self, body: models.CreateConnectionRequest, headers: Mapping[str, str] | None = None) -> models.Connection:
        payload = self._request("POST", "/api/v1/data-integration/create-connection", None, None, body, headers=headers)
        return models.deserialize_model(models.Connection, payload)

    def data_integration_connector_deleteconnection(self, headers: Mapping[str, str] | None = None) -> models.DeleteConnectionResponse:
        payload = self._request("DELETE", "/api/v1/data-integration/delete-connection", None, None, None, headers=headers)
        return models.deserialize_model(models.DeleteConnectionResponse, payload)

    def data_integration_connector_inferschema(self, body: models.InferSchemaRequest, headers: Mapping[str, str] | None = None) -> models.InferSchemaResponse:
        payload = self._request("POST", "/api/v1/data-integration/infer-schema", None, None, body, headers=headers)
        return models.deserialize_model(models.InferSchemaResponse, payload)

    def data_integration_connector_listconnections(self, headers: Mapping[str, str] | None = None) -> models.ListConnectionsResponse:
        payload = self._request("GET", "/api/v1/data-integration/list-connections", None, None, None, headers=headers)
        return models.deserialize_model(models.ListConnectionsResponse, payload)

    def data_integration_connector_syncconnection(self, body: models.SyncConnectionRequest, headers: Mapping[str, str] | None = None) -> models.SyncStatus:
        payload = self._request("POST", "/api/v1/data-integration/sync-connection", None, None, body, headers=headers)
        return models.deserialize_model(models.SyncStatus, payload)

    def data_integration_connector_testconnection(self, body: models.TestConnectionRequest, headers: Mapping[str, str] | None = None) -> models.TestConnectionResponse:
        payload = self._request("POST", "/api/v1/data-integration/test-connection", None, None, body, headers=headers)
        return models.deserialize_model(models.TestConnectionResponse, payload)

    def dataset_dataset_createdataset(self, body: models.CreateDatasetRequest, headers: Mapping[str, str] | None = None) -> models.Dataset:
        payload = self._request("POST", "/api/v1/datasets/create-dataset", None, None, body, headers=headers)
        return models.deserialize_model(models.Dataset, payload)

    def dataset_dataset_deletedataset(self, headers: Mapping[str, str] | None = None) -> models.DeleteDatasetResponse:
        payload = self._request("DELETE", "/api/v1/datasets/delete-dataset", None, None, None, headers=headers)
        return models.deserialize_model(models.DeleteDatasetResponse, payload)

    def dataset_dataset_getdataset(self, headers: Mapping[str, str] | None = None) -> models.Dataset:
        payload = self._request("GET", "/api/v1/datasets/get-dataset", None, None, None, headers=headers)
        return models.deserialize_model(models.Dataset, payload)

    def dataset_dataset_getversions(self, headers: Mapping[str, str] | None = None) -> models.GetVersionsResponse:
        payload = self._request("GET", "/api/v1/datasets/get-versions", None, None, None, headers=headers)
        return models.deserialize_model(models.GetVersionsResponse, payload)

    def dataset_dataset_listdatasets(self, headers: Mapping[str, str] | None = None) -> models.ListDatasetsResponse:
        payload = self._request("GET", "/api/v1/datasets/list-datasets", None, None, None, headers=headers)
        return models.deserialize_model(models.ListDatasetsResponse, payload)

    def dataset_dataset_previewdata(self, body: models.PreviewDataRequest, headers: Mapping[str, str] | None = None) -> models.PreviewDataResponse:
        payload = self._request("POST", "/api/v1/datasets/preview-data", None, None, body, headers=headers)
        return models.deserialize_model(models.PreviewDataResponse, payload)

    def dataset_dataset_updatedataset(self, body: models.UpdateDatasetRequest, headers: Mapping[str, str] | None = None) -> models.Dataset:
        payload = self._request("PATCH", "/api/v1/datasets/update-dataset", None, None, body, headers=headers)
        return models.deserialize_model(models.Dataset, payload)

    def notebook_notebook_createnotebook(self, body: models.CreateNotebookRequest, headers: Mapping[str, str] | None = None) -> models.Notebook:
        payload = self._request("POST", "/api/v1/notebook/create-notebook", None, None, body, headers=headers)
        return models.deserialize_model(models.Notebook, payload)

    def notebook_kernel_createsession(self, body: models.CreateSessionRequest, headers: Mapping[str, str] | None = None) -> models.Session:
        payload = self._request("POST", "/api/v1/notebook/create-session", None, None, body, headers=headers)
        return models.deserialize_model(models.Session, payload)

    def notebook_notebook_deletenotebook(self, headers: Mapping[str, str] | None = None) -> models.Notebook:
        payload = self._request("DELETE", "/api/v1/notebook/delete-notebook", None, None, None, headers=headers)
        return models.deserialize_model(models.Notebook, payload)

    def notebook_notebook_getnotebook(self, headers: Mapping[str, str] | None = None) -> models.Notebook:
        payload = self._request("GET", "/api/v1/notebook/get-notebook", None, None, None, headers=headers)
        return models.deserialize_model(models.Notebook, payload)

    def notebook_notebook_listnotebooks(self, headers: Mapping[str, str] | None = None) -> models.ListNotebooksResponse:
        payload = self._request("GET", "/api/v1/notebook/list-notebooks", None, None, None, headers=headers)
        return models.deserialize_model(models.ListNotebooksResponse, payload)

    def notebook_kernel_listsessions(self, headers: Mapping[str, str] | None = None) -> models.ListSessionsResponse:
        payload = self._request("GET", "/api/v1/notebook/list-sessions", None, None, None, headers=headers)
        return models.deserialize_model(models.ListSessionsResponse, payload)

    def notebook_kernel_stopsession(self, body: models.StopSessionRequest, headers: Mapping[str, str] | None = None) -> models.Session:
        payload = self._request("POST", "/api/v1/notebook/stop-session", None, None, body, headers=headers)
        return models.deserialize_model(models.Session, payload)

    def notebook_notebook_updatenotebook(self, body: models.UpdateNotebookRequest, headers: Mapping[str, str] | None = None) -> models.Notebook:
        payload = self._request("PATCH", "/api/v1/notebook/update-notebook", None, None, body, headers=headers)
        return models.deserialize_model(models.Notebook, payload)

    def ontology_ontology_createlinktype(self, body: models.CreateLinkTypeRequest, headers: Mapping[str, str] | None = None) -> models.LinkType:
        payload = self._request("POST", "/api/v1/ontology/create-link-type", None, None, body, headers=headers)
        return models.deserialize_model(models.LinkType, payload)

    def ontology_ontology_createobjecttype(self, body: models.CreateObjectTypeRequest, headers: Mapping[str, str] | None = None) -> models.ObjectType:
        payload = self._request("POST", "/api/v1/ontology/create-object-type", None, None, body, headers=headers)
        return models.deserialize_model(models.ObjectType, payload)

    def ontology_ontology_createproperty(self, body: models.CreatePropertyRequest, headers: Mapping[str, str] | None = None) -> models.Property:
        payload = self._request("POST", "/api/v1/ontology/create-property", None, None, body, headers=headers)
        return models.deserialize_model(models.Property, payload)

    def ontology_ontology_deletelinktype(self, headers: Mapping[str, str] | None = None) -> models.DeleteLinkTypeResponse:
        payload = self._request("DELETE", "/api/v1/ontology/delete-link-type", None, None, None, headers=headers)
        return models.deserialize_model(models.DeleteLinkTypeResponse, payload)

    def ontology_ontology_deleteobjecttype(self, headers: Mapping[str, str] | None = None) -> models.DeleteObjectTypeResponse:
        payload = self._request("DELETE", "/api/v1/ontology/delete-object-type", None, None, None, headers=headers)
        return models.deserialize_model(models.DeleteObjectTypeResponse, payload)

    def ontology_ontology_getobjecttype(self, headers: Mapping[str, str] | None = None) -> models.ObjectType:
        payload = self._request("GET", "/api/v1/ontology/get-object-type", None, None, None, headers=headers)
        return models.deserialize_model(models.ObjectType, payload)

    def ontology_ontology_listlinktypes(self, headers: Mapping[str, str] | None = None) -> models.ListLinkTypesResponse:
        payload = self._request("GET", "/api/v1/ontology/list-link-types", None, None, None, headers=headers)
        return models.deserialize_model(models.ListLinkTypesResponse, payload)

    def ontology_ontology_listobjecttypes(self, headers: Mapping[str, str] | None = None) -> models.ListObjectTypesResponse:
        payload = self._request("GET", "/api/v1/ontology/list-object-types", None, None, None, headers=headers)
        return models.deserialize_model(models.ListObjectTypesResponse, payload)

    def ontology_ontology_listproperties(self, headers: Mapping[str, str] | None = None) -> models.ListPropertiesResponse:
        payload = self._request("GET", "/api/v1/ontology/list-properties", None, None, None, headers=headers)
        return models.deserialize_model(models.ListPropertiesResponse, payload)

    def ontology_ontology_updateobjecttype(self, body: models.UpdateObjectTypeRequest, headers: Mapping[str, str] | None = None) -> models.ObjectType:
        payload = self._request("PATCH", "/api/v1/ontology/update-object-type", None, None, body, headers=headers)
        return models.deserialize_model(models.ObjectType, payload)

    def pipeline_pipeline_createpipeline(self, body: models.CreatePipelineRequest, headers: Mapping[str, str] | None = None) -> models.Pipeline:
        payload = self._request("POST", "/api/v1/pipelines/create-pipeline", None, None, body, headers=headers)
        return models.deserialize_model(models.Pipeline, payload)

    def pipeline_pipeline_deletepipeline(self, headers: Mapping[str, str] | None = None) -> models.DeletePipelineResponse:
        payload = self._request("DELETE", "/api/v1/pipelines/delete-pipeline", None, None, None, headers=headers)
        return models.deserialize_model(models.DeletePipelineResponse, payload)

    def pipeline_lineage_getdatasetlineage(self, headers: Mapping[str, str] | None = None) -> models.LineageGraph:
        payload = self._request("GET", "/api/v1/pipelines/get-dataset-lineage", None, None, None, headers=headers)
        return models.deserialize_model(models.LineageGraph, payload)

    def pipeline_lineage_getfulllineage(self, headers: Mapping[str, str] | None = None) -> models.LineageGraph:
        payload = self._request("GET", "/api/v1/pipelines/get-full-lineage", None, None, None, headers=headers)
        return models.deserialize_model(models.LineageGraph, payload)

    def pipeline_pipeline_getpipeline(self, headers: Mapping[str, str] | None = None) -> models.Pipeline:
        payload = self._request("GET", "/api/v1/pipelines/get-pipeline", None, None, None, headers=headers)
        return models.deserialize_model(models.Pipeline, payload)

    def pipeline_pipeline_getrun(self, headers: Mapping[str, str] | None = None) -> models.PipelineRun:
        payload = self._request("GET", "/api/v1/pipelines/get-run", None, None, None, headers=headers)
        return models.deserialize_model(models.PipelineRun, payload)

    def pipeline_pipeline_listpipelines(self, headers: Mapping[str, str] | None = None) -> models.ListPipelinesResponse:
        payload = self._request("GET", "/api/v1/pipelines/list-pipelines", None, None, None, headers=headers)
        return models.deserialize_model(models.ListPipelinesResponse, payload)

    def pipeline_pipeline_listruns(self, headers: Mapping[str, str] | None = None) -> models.ListRunsResponse:
        payload = self._request("GET", "/api/v1/pipelines/list-runs", None, None, None, headers=headers)
        return models.deserialize_model(models.ListRunsResponse, payload)

    def pipeline_lineage_recordlineage(self, body: models.RecordLineageRequest, headers: Mapping[str, str] | None = None) -> models.RecordLineageResponse:
        payload = self._request("POST", "/api/v1/pipelines/record-lineage", None, None, body, headers=headers)
        return models.deserialize_model(models.RecordLineageResponse, payload)

    def pipeline_pipeline_triggerrun(self, body: models.TriggerRunRequest, headers: Mapping[str, str] | None = None) -> models.PipelineRun:
        payload = self._request("POST", "/api/v1/pipelines/trigger-run", None, None, body, headers=headers)
        return models.deserialize_model(models.PipelineRun, payload)

    def pipeline_pipeline_updatepipeline(self, body: models.UpdatePipelineRequest, headers: Mapping[str, str] | None = None) -> models.Pipeline:
        payload = self._request("PATCH", "/api/v1/pipelines/update-pipeline", None, None, body, headers=headers)
        return models.deserialize_model(models.Pipeline, payload)

    def query_query_deletesavedquery(self, headers: Mapping[str, str] | None = None) -> models.DeleteSavedQueryResponse:
        payload = self._request("DELETE", "/api/v1/queries/delete-saved-query", None, None, None, headers=headers)
        return models.deserialize_model(models.DeleteSavedQueryResponse, payload)

    def query_query_executequery(self, body: models.ExecuteQueryRequest, headers: Mapping[str, str] | None = None) -> models.QueryResult:
        payload = self._request("POST", "/api/v1/queries/execute-query", None, None, body, headers=headers)
        return models.deserialize_model(models.QueryResult, payload)

    def query_query_explainquery(self, body: models.ExplainQueryRequest, headers: Mapping[str, str] | None = None) -> models.ExplainQueryResponse:
        payload = self._request("POST", "/api/v1/queries/explain-query", None, None, body, headers=headers)
        return models.deserialize_model(models.ExplainQueryResponse, payload)

    def query_query_listsavedqueries(self, headers: Mapping[str, str] | None = None) -> models.ListSavedQueriesResponse:
        payload = self._request("GET", "/api/v1/queries/list-saved-queries", None, None, None, headers=headers)
        return models.deserialize_model(models.ListSavedQueriesResponse, payload)

    def query_query_savequery(self, body: models.SaveQueryRequest, headers: Mapping[str, str] | None = None) -> models.SavedQuery:
        payload = self._request("POST", "/api/v1/queries/save-query", None, None, body, headers=headers)
        return models.deserialize_model(models.SavedQuery, payload)

    def admin_v2_getcontrolpanel(self, headers: Mapping[str, str] | None = None) -> models.ControlPanelSettings:
        payload = self._request("GET", "/api/v2/admin/control-panel", None, None, None, headers=headers)
        return models.deserialize_model(models.ControlPanelSettings, payload)

    def admin_v2_updatecontrolpanel(self, body: models.UpdateControlPanelRequest, headers: Mapping[str, str] | None = None) -> models.ControlPanelSettings:
        payload = self._request("PUT", "/api/v2/admin/control-panel", None, None, body, headers=headers)
        return models.deserialize_model(models.ControlPanelSettings, payload)

    def admin_v2_listgroups(self, headers: Mapping[str, str] | None = None) -> models.AdminGroupsListResponse:
        payload = self._request("GET", "/api/v2/admin/groups", None, None, None, headers=headers)
        return models.deserialize_model(models.AdminGroupsListResponse, payload)

    def admin_v2_creategroup(self, body: models.CreateGroupRequest, headers: Mapping[str, str] | None = None) -> models.GroupResponse:
        payload = self._request("POST", "/api/v2/admin/groups", None, None, body, headers=headers)
        return models.deserialize_model(models.GroupResponse, payload)

    def admin_v2_updategroup(self, id: str, body: models.UpdateGroupRequest, headers: Mapping[str, str] | None = None) -> models.GroupResponse:
        payload = self._request("PUT", "/api/v2/admin/groups/{id}", {"id": id}, None, body, headers=headers)
        return models.deserialize_model(models.GroupResponse, payload)

    def admin_v2_listpermissions(self, headers: Mapping[str, str] | None = None) -> models.AdminPermissionsListResponse:
        payload = self._request("GET", "/api/v2/admin/permissions", None, None, None, headers=headers)
        return models.deserialize_model(models.AdminPermissionsListResponse, payload)

    def admin_v2_createpermission(self, body: models.CreatePermissionRequest, headers: Mapping[str, str] | None = None) -> models.Permission:
        payload = self._request("POST", "/api/v2/admin/permissions", None, None, body, headers=headers)
        return models.deserialize_model(models.Permission, payload)

    def admin_v2_listpolicies(self, headers: Mapping[str, str] | None = None) -> models.AdminPoliciesListResponse:
        payload = self._request("GET", "/api/v2/admin/policies", None, None, None, headers=headers)
        return models.deserialize_model(models.AdminPoliciesListResponse, payload)

    def admin_v2_createpolicy(self, body: models.UpsertPolicyRequest, headers: Mapping[str, str] | None = None) -> models.Policy:
        payload = self._request("POST", "/api/v2/admin/policies", None, None, body, headers=headers)
        return models.deserialize_model(models.Policy, payload)

    def admin_v2_evaluatepolicy(self, body: models.EvaluatePolicyRequest, headers: Mapping[str, str] | None = None) -> models.PolicyEvaluationResult:
        payload = self._request("POST", "/api/v2/admin/policies/evaluate", None, None, body, headers=headers)
        return models.deserialize_model(models.PolicyEvaluationResult, payload)

    def admin_v2_updatepolicy(self, id: str, body: models.UpsertPolicyRequest, headers: Mapping[str, str] | None = None) -> models.Policy:
        payload = self._request("PATCH", "/api/v2/admin/policies/{id}", {"id": id}, None, body, headers=headers)
        return models.deserialize_model(models.Policy, payload)

    def admin_v2_listroles(self, headers: Mapping[str, str] | None = None) -> models.AdminRolesListResponse:
        payload = self._request("GET", "/api/v2/admin/roles", None, None, None, headers=headers)
        return models.deserialize_model(models.AdminRolesListResponse, payload)

    def admin_v2_createrole(self, body: models.CreateRoleRequest, headers: Mapping[str, str] | None = None) -> models.RoleResponse:
        payload = self._request("POST", "/api/v2/admin/roles", None, None, body, headers=headers)
        return models.deserialize_model(models.RoleResponse, payload)

    def admin_v2_updaterole(self, id: str, body: models.UpdateRoleRequest, headers: Mapping[str, str] | None = None) -> models.RoleResponse:
        payload = self._request("PUT", "/api/v2/admin/roles/{id}", {"id": id}, None, body, headers=headers)
        return models.deserialize_model(models.RoleResponse, payload)

    def admin_v2_listusers(self, headers: Mapping[str, str] | None = None) -> models.AdminUsersListResponse:
        payload = self._request("GET", "/api/v2/admin/users", None, None, None, headers=headers)
        return models.deserialize_model(models.AdminUsersListResponse, payload)

    def admin_v2_getcurrentuser(self, headers: Mapping[str, str] | None = None) -> models.UserResponse:
        payload = self._request("GET", "/api/v2/admin/users/me", None, None, None, headers=headers)
        return models.deserialize_model(models.UserResponse, payload)

    def admin_v2_updateuser(self, id: str, body: models.UpdateUserRequest, headers: Mapping[str, str] | None = None) -> models.UserResponse:
        payload = self._request("PATCH", "/api/v2/admin/users/{id}", {"id": id}, None, body, headers=headers)
        return models.deserialize_model(models.UserResponse, payload)

    def filesystem_v2_getdatasetfilesystem(self, dataset_id: str, path: str | None = None, headers: Mapping[str, str] | None = None) -> models.FilesystemListResponse:
        payload = self._request("GET", "/api/v2/filesystem/datasets/{dataset_id}", {"dataset_id": dataset_id}, {"path": path}, None, headers=headers)
        return models.deserialize_model(models.FilesystemListResponse, payload)
